import type { ComponentType } from 'react';
import type { StoryObj } from '@storybook/react-vite';
import {
  MDSBottomNavigation,
  MDSIcon,
} from '@mds/components';
import type {
  MDSBottomNavigationProps,
  MDSBottomNavigationBackground,
} from '@mds/components';
import { ComponentDocs } from '../docs-template';
import type { MDSMeta } from '../docs-template';

// MDSBottomNavigation is a compound component:
//   <MDSBottomNavigation aria-label="Primary" background="standard">
//     <MDSBottomNavigation.Item icon={...} selected>Home</MDSBottomNavigation.Item>
//     <MDSBottomNavigation.Item icon={...} showBadge>Inbox</MDSBottomNavigation.Item>
//     <MDSBottomNavigation.Item icon={...} href="/profile">Profile</MDSBottomNavigation.Item>
//   </MDSBottomNavigation>
//
// • Renders <nav aria-label="..."> with items distributed equally (flex 1 0).
// • Items default to <a> when given an `href`, otherwise <button type="button">.
// • The selection bar is always rendered; visibility is driven by
//   data-selected / :hover / :active state so consumers don't have to think
//   about hover-state styling.
// • showBadge renders the 10px accent dot at the top-right of the icon —
//   for an "unread / has-updates" indicator. Counted badges should be
//   composed with MDSBadge externally.

const ICON_OPTIONS = [
  'house',
  'magnifying-glass',
  'chat-circle',
  'bell',
  'user',
  'gear',
  'heart',
] as const;

type IconName = (typeof ICON_OPTIONS)[number];

type ProxyArgs = {
  itemCount: 2 | 3 | 4 | 5;
  selectedIndex: 0 | 1 | 2 | 3 | 4;
  badgeIndex: -1 | 0 | 1 | 2 | 3 | 4;
  hideLabels: boolean;
  background: MDSBottomNavigationBackground;
};

const LABEL_BY_ICON: Record<IconName, string> = {
  house: 'Home',
  'magnifying-glass': 'Search',
  'chat-circle': 'Messages',
  bell: 'Alerts',
  user: 'Profile',
  gear: 'Settings',
  heart: 'Favourites',
};

// Cast `component` to ComponentType so the meta type doesn't reference the
// unexported inner `MDSBottomNavigationRoot` function (same approach as
// MDSBreadcrumb).
const BottomNavAsComponent = MDSBottomNavigation as unknown as ComponentType<
  MDSBottomNavigationProps & ProxyArgs
>;

const meta = {
  title: 'Components/MDSBottomNavigation',
  component: BottomNavAsComponent,
  tags: ['autodocs'],
  args: {
    itemCount: 5,
    selectedIndex: 0,
    badgeIndex: 2,
    hideLabels: false,
    background: 'standard',
    'aria-label': 'Primary',
    // Children are generated by `render` from the playground args; this
    // `null` satisfies the required `children` prop at the type level —
    // Storybook never actually forwards it to the component.
    children: null,
  },
  argTypes: {
    itemCount: {
      control: { type: 'inline-radio' },
      options: [2, 3, 4, 5],
      description:
        'Story-only — how many items the playground renders (2–5, matching Figma variants).',
    },
    selectedIndex: {
      control: { type: 'number', min: 0, max: 4, step: 1 },
      description:
        'Story-only — which item is marked `selected` (`aria-current="page"`).',
    },
    badgeIndex: {
      control: { type: 'number', min: -1, max: 4, step: 1 },
      description:
        'Story-only — which item shows the "has updates" badge dot. `-1` shows none.',
    },
    hideLabels: {
      control: { type: 'boolean' },
      description:
        'Story-only — when true, every item passes `hideLabel` so only icons render. The label text is preserved on the `aria-label` of each item so the navigation stays accessible.',
    },
    background: {
      control: { type: 'inline-radio' },
      options: ['standard', 'secondary'],
      description:
        '`standard` = `--mds-colours-basic-background` (white) · `secondary` = `--mds-colours-basic-accent-secondary` (pale lavender on the neutral palette).',
    },
    'aria-label': {
      control: { type: 'text' },
      description:
        'Required accessible name for the `<nav>` landmark.',
      table: { category: 'Accessibility' },
    },
    children: { table: { disable: true } },
  },
  render: (args) => {
    const {
      itemCount,
      selectedIndex,
      badgeIndex,
      hideLabels,
      background,
      'aria-label': ariaLabel,
    } = args;
    const icons = ICON_OPTIONS.slice(0, itemCount);

    return (
      <div style={{ width: 335 }}>
        <MDSBottomNavigation aria-label={ariaLabel} background={background}>
          {icons.map((iconName, idx) => {
            const label = LABEL_BY_ICON[iconName];
            return (
              <MDSBottomNavigation.Item
                key={iconName}
                href={`#${iconName}`}
                icon={<MDSIcon name={iconName} />}
                selected={idx === selectedIndex}
                showBadge={idx === badgeIndex}
                hideLabel={hideLabels}
                aria-label={hideLabels ? label : undefined}
              >
                {label}
              </MDSBottomNavigation.Item>
            );
          })}
        </MDSBottomNavigation>
      </div>
    );
  },
  parameters: {
    docs: { page: ComponentDocs },
    layout: 'centered',
    mds: {
      docs: {
        summary:
          'A horizontal navigation bar for the bottom of a mobile or compact viewport. Holds 2–5 items, each pairing an icon with an optional label and an optional "has updates" badge dot. The selected item shows a 4px accent bar at the top; hovered and pressed states reveal the same bar in subdued/dark variants.',
        usage: { importFrom: '@mds/components' },
        guidelines: {
          use: [
            'As the primary top-level navigation on mobile and compact viewports where ≤ 5 destinations need to remain reachable from any screen.',
            'When destinations are peer-level — bottom nav surfaces siblings, not hierarchy. Pair with `MDSBreadcrumb` or a top app bar for in-section navigation.',
            'For destinations that benefit from a recognisable icon — bottom-nav items are tap targets first and labels second. Icons must be meaningful on their own; the label is a reinforcement, not a replacement.',
            'With `showBadge` for "has unread / has updates" indicators where the count is not the message. For numeric counts, compose `MDSBadge` next to the icon instead.',
          ],
          avoid: [
            'For more than 5 destinations — the bar becomes cramped, taps less accurate, and the visual hierarchy collapses. Use an overflow menu or rethink the IA.',
            'For one-off actions (compose, scan, capture). Bottom nav is for navigation. Use a FAB or contextual action surface for actions.',
            'As the only navigation surface on a long page — pair with breadcrumbs or section headers so the user knows where they are within the destination.',
            'Hiding labels by default. The icon-only mode (`hideLabel`) is a compact variant; reserve it for narrow viewports or expert users. Always pass `aria-label` on each item when hiding labels.',
          ],
        },
        details: {
          behaviour:
            'Renders `<nav aria-label="...">` with each child as a direct flex sibling (`flex: 1 0 0`) so 2/3/4/5-item bars all distribute their items equally. Items render as `<a>` when given an `href` and `<button type="button">` otherwise; the polymorphism contract\'s `render` prop lets you swap in router-aware link components. The selection bar is always present in the DOM; CSS state (`[data-selected]`, `:hover`, `:active`) controls its colour — selected items use the accent, unselected items reveal the text colour on hover/press for a subtle affordance.',
          accessibility:
            'Uses the `<nav>` landmark with a required `aria-label`. Items render as real `<a>`/`<button>` so keyboard focus, the focus ring, and assistive-tech announcements work without any extra wiring. The selected item is marked `aria-current="page"`. Each item honours the system\'s 48 px minimum tappable area on every side. Icons are wrapped with `aria-hidden`, so the label (or the per-item `aria-label` when `hideLabel` is set) is the sole accessible name. The badge dot is decorative (`aria-hidden`) — pair it with an item-level `aria-label` like "Inbox, 3 unread" when the indicator carries information.',
          animation:
            'No animation on the bar itself — state changes (selection, hover, press) are instant colour swaps. `prefers-reduced-motion: reduce` is honoured (no transitions or animations declared).',
          gotchas:
            'The selection bar is rendered as a sibling slot (`data-slot="selection-bar"`) inside every item, not just the selected one — visibility is driven by CSS so consumers can override the appearance per state via `--MDSBottomNavigationItem-selection-bar-fill`. Items with `selected` set `cursor: default`; consumers wiring router-level navigation should still attach `onClick` and prevent the default navigation on the current item to avoid unnecessary route churn.',
        },
        related: [
          { name: 'MDSBreadcrumb', href: '/?path=/docs/components-mdsbreadcrumb--docs' },
          { name: 'MDSIcon', href: '/?path=/docs/components-mdsicon--docs' },
          { name: 'MDSBadge', href: '/?path=/docs/components-mdsbadge--docs' },
        ],
      },
    },
  },
} satisfies MDSMeta<ComponentType<MDSBottomNavigationProps>, ProxyArgs>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const TwoItems: Story = {
  args: { itemCount: 2, selectedIndex: 0, badgeIndex: -1 },
};

export const ThreeItems: Story = {
  args: { itemCount: 3, selectedIndex: 1, badgeIndex: -1 },
};

export const FourItems: Story = {
  args: { itemCount: 4, selectedIndex: 0, badgeIndex: 2 },
};

export const FiveItems: Story = {
  args: { itemCount: 5, selectedIndex: 0, badgeIndex: 2 },
};

export const SecondaryBackground: Story = {
  args: { background: 'secondary', itemCount: 5, selectedIndex: 0, badgeIndex: 2 },
  parameters: {
    docs: {
      description: {
        story:
          'Pale lavender surface — `--mds-colours-basic-accent-secondary`. Use when the bottom nav needs to stand off from a white page beneath it without picking up the accent colour.',
      },
    },
  },
};

export const WithBadge: Story = {
  args: { itemCount: 5, selectedIndex: 0, badgeIndex: 3 },
  parameters: {
    docs: {
      description: {
        story:
          'A single item surfaces a small accent dot via `showBadge` — the "has updates" indicator. Decorative by default; pair with an item-level `aria-label` like "Alerts, 3 new" when the dot carries information.',
      },
    },
  },
};

export const IconOnly: Story = {
  args: { itemCount: 5, selectedIndex: 0, badgeIndex: -1, hideLabels: true },
  parameters: {
    docs: {
      description: {
        story:
          'Compact variant — every item passes `hideLabel`. The label text is preserved on `aria-label` of each item so screen readers still announce the destination.',
      },
    },
  },
};

export const StaticBar: Story = {
  args: { itemCount: 5 },
  render: () => (
    <div style={{ width: 335 }}>
      <MDSBottomNavigation aria-label="Primary">
        <MDSBottomNavigation.Item href="/" icon={<MDSIcon name="house" />} selected>
          Home
        </MDSBottomNavigation.Item>
        <MDSBottomNavigation.Item href="/search" icon={<MDSIcon name="magnifying-glass" />}>
          Search
        </MDSBottomNavigation.Item>
        <MDSBottomNavigation.Item href="/inbox" icon={<MDSIcon name="chat-circle" />} showBadge>
          Messages
        </MDSBottomNavigation.Item>
        <MDSBottomNavigation.Item href="/alerts" icon={<MDSIcon name="bell" />}>
          Alerts
        </MDSBottomNavigation.Item>
        <MDSBottomNavigation.Item href="/profile" icon={<MDSIcon name="user" />}>
          Profile
        </MDSBottomNavigation.Item>
      </MDSBottomNavigation>
    </div>
  ),
  parameters: {
    docs: {
      description: {
        story:
          'A realistic, statically composed bar. Use this shape in real code — pass `href` on every item, let `selected` mark the current page, and add `showBadge` for "has updates" affordances.',
      },
    },
  },
};
