import type { ComponentType } from 'react';
import type { StoryObj } from '@storybook/react-vite';
import { MDSBreadcrumb } from '@mds/components';
import type { MDSBreadcrumbProps } from '@mds/components';
import { ComponentDocs } from '../docs-template';
import type { MDSMeta } from '../docs-template';

// MDSBreadcrumb is a compound component:
//   <MDSBreadcrumb maxItems={4}>
//     <MDSBreadcrumb.Item href="/">Home</MDSBreadcrumb.Item>
//     <MDSBreadcrumb.Item href="/a">Section</MDSBreadcrumb.Item>
//     <MDSBreadcrumb.Item>Current</MDSBreadcrumb.Item>
//   </MDSBreadcrumb>
//
// • Renders <nav aria-label="Breadcrumb"><ol/></nav>
// • Last child is auto-marked aria-current="page" and rendered as <span>
// • Items with no href render as <span> (escape hatch for disabled crumbs)
// • When count > maxItems (default 4), middle items collapse into a
//   Base UI Menu overflow — first / overflow / second-to-last / last
// • maxItems is clamped to a minimum of 2

// Story-only proxy controls — the real component takes children, but
// the playground generates them from `pathCount` + a label template.
type ProxyArgs = {
  pathCount: 2 | 3 | 4 | 5 | 6 | 7;
};

const LABELS = [
  'Level 1',
  'Level 2',
  'Level 3',
  'Level 4',
  'Level 5',
  'Level 6',
  'Level 7',
] as const;

// Cast `component` to a `ComponentType<Props>` shape so the inferred meta
// type doesn't reference the unexported inner `MDSBreadcrumbRoot` function —
// `typeof MDSBreadcrumb` otherwise expands to `typeof MDSBreadcrumbRoot & {...}`
// which TypeScript can't name when emitting the meta's declaration.
const BreadcrumbAsComponent =
  MDSBreadcrumb as unknown as ComponentType<MDSBreadcrumbProps & ProxyArgs>;

const meta = {
  title: 'Components/MDSBreadcrumb',
  component: BreadcrumbAsComponent,
  tags: ['autodocs'],
  args: {
    pathCount: 4,
    maxItems: 4,
    'aria-label': 'Breadcrumb',
    // Children are generated by the `render` function from `pathCount`.
    // This `null` satisfies the required `children` prop at the type level —
    // Storybook never actually passes it to the component.
    children: null,
  },
  argTypes: {
    pathCount: {
      control: { type: 'inline-radio' },
      options: [2, 3, 4, 5, 6, 7],
      description:
        'Story-only — how many breadcrumb items the playground renders. Increase past `maxItems` to see the overflow.',
    },
    maxItems: {
      control: { type: 'number', min: 2, max: 8, step: 1 },
      description:
        'Visible item budget. When the rendered count exceeds this, middle items collapse into the overflow menu. Clamped to a minimum of 2.',
    },
    'aria-label': {
      control: { type: 'text' },
      description:
        'Accessible name of the navigation landmark. Defaults to `"Breadcrumb"`.',
      table: { category: 'Accessibility' },
    },
    children: { table: { disable: true } },
  },
  render: (args) => {
    const { pathCount, maxItems, 'aria-label': ariaLabel } = args;
    const labels = Array.from({ length: pathCount }, (_, i) => LABELS[i] ?? `Level ${i + 1}`);
    const lastIndex = labels.length - 1;

    return (
      <MDSBreadcrumb maxItems={maxItems} aria-label={ariaLabel}>
        {labels.map((label, idx) => {
          const isLast = idx === lastIndex;
          // Last item: no href → MDSBreadcrumb renders <span aria-current="page">.
          // Others get a synthetic href so they render as real <a> links.
          return isLast ? (
            <MDSBreadcrumb.Item key={label}>{label}</MDSBreadcrumb.Item>
          ) : (
            <MDSBreadcrumb.Item key={label} href={`#${label.toLowerCase().replace(/\s+/g, '-')}`}>
              {label}
            </MDSBreadcrumb.Item>
          );
        })}
      </MDSBreadcrumb>
    );
  },
  parameters: {
    docs: { page: ComponentDocs },
    mds: {
      docs: {
        summary:
          'A breadcrumb trail showing where the user is in a hierarchy. The last item is automatically marked as the current page; longer trails collapse middle items into an overflow menu.',
        usage: { importFrom: '@mds/components' },
        guidelines: {
          use: [
            'On pages deeper than two levels in a hierarchy where the user needs an at-a-glance "you are here" plus a fast way to step back up.',
            'For products, content libraries, file managers, or admin consoles where parent context is meaningful and reachable.',
            'When the trail is short and stable — let `maxItems` collapse the middle when paths get longer.',
            'Pair with the document `<h1>` rather than replace it — breadcrumb is supplemental wayfinding, not the page title.',
          ],
          avoid: [
            'On flat sites or top-level marketing pages where there is no meaningful hierarchy to surface.',
            'As primary navigation — the trail is a record of where the user has been, not a list of where they can go.',
            'Replacing the page title — keep both. The breadcrumb provides context; the heading provides identity.',
            'Hiding the last (current) item — the WAI-ARIA Breadcrumb Pattern requires the current page to remain in the trail and be marked `aria-current="page"`.',
          ],
        },
        details: {
          behaviour:
            'Renders `<nav aria-label="Breadcrumb"><ol/></nav>` with `/` separators between items. The last `MDSBreadcrumb.Item` is automatically the current page — rendered as a `<span aria-current="page">` regardless of `href`. Items with `href` render as `<a>`; items without `href` render as a non-link `<span>` (useful for unreachable crumbs). When `Children.count(children) > maxItems` AND there is at least one item to collapse, the component renders `[first] / [overflow] / [second-to-last] / [last]` — middle items go inside a Base UI Menu popup activated by a `dots-three` trigger.',
          accessibility:
            'Follows the WAI-ARIA Breadcrumb Pattern: a `<nav>` landmark with a labelled `<ol>`, each item in an `<li>`, current page marked with `aria-current="page"`. Separators are `aria-hidden`. The overflow trigger is a real `<button>` with an explicit `aria-label="Show collapsed breadcrumbs"`; Base UI Menu adds the `aria-haspopup` / `aria-expanded` / `aria-controls` wiring automatically. Each item cell honours the system\'s 48 px minimum tappable area.',
          animation:
            'No motion on the trail itself. The overflow popup uses Base UI Menu\'s open/close animation — opacity + transform via `data-starting-style` / `data-ending-style`. All transitions are suppressed under `prefers-reduced-motion: reduce`.',
          gotchas:
            '`maxItems` is clamped to a minimum of 2 — passing `0` or `1` is treated as `2`. The overflow only fires when there is at least one item to collapse, so a 3-item trail with `maxItems={2}` renders flat (no degenerate empty menu). The `current` prop on `MDSBreadcrumb.Item` is internal — the parent sets it based on position; you cannot opt out of last-item-current behaviour by passing `current` yourself.',
        },
        related: [
          { name: 'MDSText', href: '/?path=/docs/components-mdstext--docs' },
          { name: 'MDSIcon', href: '/?path=/docs/components-mdsicon--docs' },
        ],
      },
    },
  },
  // `typeof MDSBreadcrumb` references the inner `MDSBreadcrumbRoot` function
  // which isn't part of the public export surface, so TypeScript can't name
  // it when emitting declarations. Use `ComponentType<Props>` to sidestep
  // the reference entirely — same type contract for Storybook.
} satisfies MDSMeta<ComponentType<MDSBreadcrumbProps>, ProxyArgs>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const TwoLevels: Story = {
  args: { pathCount: 2 },
};

export const ThreeLevels: Story = {
  args: { pathCount: 3 },
};

export const FourLevels: Story = {
  args: { pathCount: 4 },
};

export const FiveLevelsWithOverflow: Story = {
  args: { pathCount: 5 },
  parameters: {
    docs: {
      description: {
        story:
          'Once the visible count exceeds `maxItems` (default 4), middle items collapse into a `…` overflow button. Click the button to reveal the collapsed segments inside a Base UI Menu popup.',
      },
    },
  },
};

export const SixLevelsWithOverflow: Story = {
  args: { pathCount: 6 },
};

export const SevenLevelsWithOverflow: Story = {
  args: { pathCount: 7 },
};

export const CustomMaxItems: Story = {
  args: { pathCount: 6, maxItems: 5 },
  parameters: {
    docs: {
      description: {
        story:
          'Raise `maxItems` when a longer trail benefits the user (e.g. desktop wide layouts). It keeps more crumbs visible before collapsing. `maxItems` is clamped at 2 minimum.',
      },
    },
  },
};

export const CustomLabel: Story = {
  args: { 'aria-label': 'You are here' },
  parameters: {
    docs: {
      description: {
        story:
          'Override the `<nav>` landmark label when the default "Breadcrumb" is not descriptive enough in your language or product.',
      },
    },
  },
};

export const StaticTrail: Story = {
  args: { pathCount: 4 },
  render: () => (
    <MDSBreadcrumb>
      <MDSBreadcrumb.Item href="/">Level 1</MDSBreadcrumb.Item>
      <MDSBreadcrumb.Item href="/products">Level 2</MDSBreadcrumb.Item>
      <MDSBreadcrumb.Item href="/products/audio">Level 3</MDSBreadcrumb.Item>
      <MDSBreadcrumb.Item>Current Page</MDSBreadcrumb.Item>
    </MDSBreadcrumb>
  ),
  parameters: {
    docs: {
      description: {
        story:
          'A realistic, statically composed trail. Use this shape in real code — pass `href` on every item except the last, and let MDSBreadcrumb mark the current page automatically.',
      },
    },
  },
};
