import type { ComponentType } from 'react';
import type { StoryObj } from '@storybook/react-vite';
import { MDSFlyout, MDSIcon } from '@mds/components';
import type { MDSFlyoutProps } from '@mds/components';
import { ComponentDocs } from '../docs-template';
import type { MDSMeta } from '../docs-template';

// MDSFlyout is a presentational popup card — a white surface with a 1px
// stroke and a `radius-full` corner. It accepts arbitrary children, plus
// an MDSFlyout.Item subcomponent that matches Figma's "Dropdown Item"
// (48px min-height pill with a 16px trailing icon slot and a hover state).
//
// MDSFlyout owns shell + item styling only — it does NOT own positioning,
// trigger wiring, or keyboard navigation. Pair it with Base UI's Menu or
// Popover when you need those behaviours (see MDSBreadcrumb's overflow
// menu for the canonical usage: `<MDSFlyout render={<Menu.Popup />} />`).

type ProxyArgs = {
  itemCount: 2 | 3 | 4 | 5 | 6;
  scrollable: boolean;
};

const LABELS = [
  'Level 1',
  'Level 2',
  'Level 3',
  'Level 4',
  'Level 5',
  'Level 6',
];

// Cast `component` to a `ComponentType<Props>` shape so the inferred meta
// type doesn't reference the unexported inner `MDSFlyoutRoot` function —
// `typeof MDSFlyout` otherwise expands in a way TypeScript can't name
// when emitting the meta's declaration.
const FlyoutAsComponent =
  MDSFlyout as unknown as ComponentType<MDSFlyoutProps & ProxyArgs>;

const meta = {
  title: 'Components/MDSFlyout',
  component: FlyoutAsComponent,
  tags: ['autodocs'],
  args: {
    itemCount: 2,
    scrollable: false,
    // Children are generated by the `render` function from `itemCount`.
    children: null,
  },
  argTypes: {
    itemCount: {
      control: { type: 'inline-radio' },
      options: [2, 3, 4, 5, 6],
      description:
        'Story-only — how many dropdown items the playground renders. The flyout itself accepts arbitrary children.',
    },
    scrollable: {
      control: { type: 'boolean' },
      description:
        'Story-only — when `true`, sets `maxHeight={144}` so the content scrolls and the styled scrollbar appears.',
    },
    maxHeight: {
      control: { type: 'text' },
      description:
        'Cap the flyout height and enable internal scrolling. Accepts any CSS length (number for px, or strings like `"50vh"`).',
    },
    render: { table: { disable: true } },
    children: { table: { disable: true } },
  },
  render: (args) => {
    const { itemCount, scrollable } = args;
    const items = Array.from(
      { length: itemCount },
      (_, i) => LABELS[i] ?? `Item ${i + 1}`,
    );
    return (
      <MDSFlyout
        maxHeight={scrollable ? 144 : args.maxHeight}
        style={{ width: 200 }}
      >
        {items.map((label) => (
          <MDSFlyout.Item key={label}>{label}</MDSFlyout.Item>
        ))}
      </MDSFlyout>
    );
  },
  parameters: {
    docs: { page: ComponentDocs },
    mds: {
      docs: {
        summary:
          'A presentational popup card. Combine with Base UI Menu / Popover for real floating behaviour. Ships an MDSFlyout.Item subcomponent that matches Figma\'s "Dropdown Item" pill.',
        usage: { importFrom: '@mds/components' },
        guidelines: {
          use: [
            'As the visual shell for menus, dropdowns, or any anchored card surfaces — e.g. MDSBreadcrumb\'s overflow popup, future Select / Combobox menus, or custom Popover content.',
            'With MDSFlyout.Item for dropdown rows that share the design-system pill, hover, and 48px tappable area.',
            'With `maxHeight` when the content list might grow long — the browser renders a styled scrollbar matching the Figma "Show Scrollbar=true" frame.',
            'Composed via `render={<Menu.Popup />}` (or `<Popover.Popup />`, etc.) so the flyout styling layers cleanly on Base UI primitives.',
          ],
          avoid: [
            'Building floating behaviour from scratch — let Base UI Menu / Popover own the trigger, positioning, focus management, and click-outside.',
            'Using the flyout as a generic Card. Cards are full-width surfaces; flyouts are anchored, transient overlays.',
            'Hardcoding widths — let the consumer size the flyout (via inline `style` or className) so it can match its trigger.',
            'Stacking dropdown items inside the flyout without using MDSFlyout.Item — the pill shape, hover state, focus ring, and minimum-tappable-area are part of the contract.',
          ],
        },
        details: {
          behaviour:
            'MDSFlyout is presentational — a `<div>` with the shell styling and a `render` prop for polymorphism. MDSFlyout.Item is a polymorphic `<button>` with a leading label and a 16px trailing icon slot; pass `icon={<MDSIcon …/>}` to fill the slot. Both subcomponents forward arbitrary HTML attributes onto the rendered element via `useRender`, so consumers can attach IDs, ARIA props, event handlers, or Base UI render props.',
          accessibility:
            'MDSFlyout itself has no implicit role — it inherits the role of whatever it renders as (`<div>` by default, `<Menu.Popup>` when composed). MDSFlyout.Item renders a real `<button type="button">` by default, with a visible focus ring (2px accent outline). The CSS responds to `[data-highlighted]` so Base UI Menu\'s keyboard navigation lights up the same hover background.',
          animation:
            'No motion on the shell itself. When composed with Base UI Menu / Popover, the parent owns the open/close animation via `data-starting-style` / `data-ending-style`. All transitions are suppressed under `prefers-reduced-motion: reduce`.',
          gotchas:
            'The card is purely presentational. It does not anchor itself to a trigger, manage focus, or handle escape-to-close — pair it with Base UI Menu or Popover for that. The styled scrollbar only renders when `maxHeight` is set; otherwise the flyout grows to fit its content with `overflow: hidden`. When portalled (e.g. inside `<Menu.Portal>`), component-scoped vars must be declared on the flyout element itself — the portal escapes any ancestor `.root` cascade.',
        },
        related: [
          { name: 'MDSBreadcrumb', href: '/?path=/docs/components-mdsbreadcrumb--docs' },
          { name: 'MDSIcon', href: '/?path=/docs/components-mdsicon--docs' },
          { name: 'MDSText', href: '/?path=/docs/components-mdstext--docs' },
        ],
      },
    },
  },
} satisfies MDSMeta<ComponentType<MDSFlyoutProps>, ProxyArgs>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const TwoItems: Story = {
  args: { itemCount: 2 },
};

export const ThreeItems: Story = {
  args: { itemCount: 3 },
};

export const SixItems: Story = {
  args: { itemCount: 6 },
};

export const Scrollable: Story = {
  args: { itemCount: 6, scrollable: true },
  parameters: {
    docs: {
      description: {
        story:
          'When `maxHeight` is set, the flyout becomes scrollable. The native scrollbar is styled to match the Figma "Show Scrollbar=true" frame — an 8px-wide rounded scrim thumb.',
      },
    },
  },
};

export const WithTrailingIcons: Story = {
  render: () => (
    <MDSFlyout style={{ width: 220 }}>
      <MDSFlyout.Item icon={<MDSIcon name="caret-right" size="small" />}>
        Level 1
      </MDSFlyout.Item>
      <MDSFlyout.Item icon={<MDSIcon name="caret-right" size="small" />}>
        Level 2
      </MDSFlyout.Item>
      <MDSFlyout.Item icon={<MDSIcon name="caret-right" size="small" />}>
        Level 3
      </MDSFlyout.Item>
    </MDSFlyout>
  ),
  parameters: {
    docs: {
      description: {
        story:
          'Each `MDSFlyout.Item` has a 16px trailing icon slot. Pass any 16px node via `icon`; an empty slot stays present (and aria-hidden) so labels align across the column.',
      },
    },
  },
};

export const AsLinks: Story = {
  render: () => (
    <MDSFlyout style={{ width: 200 }}>
      <MDSFlyout.Item render={<a href="#level-1" />}>Level 1</MDSFlyout.Item>
      <MDSFlyout.Item render={<a href="#level-2" />}>Level 2</MDSFlyout.Item>
      <MDSFlyout.Item render={<a href="#level-3" />}>Level 3</MDSFlyout.Item>
    </MDSFlyout>
  ),
  parameters: {
    docs: {
      description: {
        story:
          'Use `render={<a href="…" />}` to render each item as a real anchor. The pill styling, focus ring, and hover state all carry over unchanged.',
      },
    },
  },
};

export const LongLabels: Story = {
  render: () => (
    <MDSFlyout style={{ width: 200 }}>
      <MDSFlyout.Item>Short</MDSFlyout.Item>
      <MDSFlyout.Item>
        A very long label that should truncate with an ellipsis
      </MDSFlyout.Item>
      <MDSFlyout.Item>Another item</MDSFlyout.Item>
    </MDSFlyout>
  ),
  parameters: {
    docs: {
      description: {
        story:
          'Labels truncate with an ellipsis when they exceed the flyout width — matches Figma\'s `text-ellipsis` + `whitespace-nowrap` on the Dropdown Item label.',
      },
    },
  },
};
